### ISSUE TITLE
list templates issue

### ISSUE THREAD

**Issue by iamgoki** [maharanasarkar/whatsapp-connector-rasa#4]
Is there is any possible way to use list templates in custom connector.py file like button templates.

**Comment by maharanasarkar** [comment]
@iamgoki I am not sure if that can be possible with this custom connector because this connector uses `heyoo` as a package to communicate with the WhatsApp API, as of my knowledge `heyoo` does not have the support for list templates.

Below is the list of supported features provided by heyoo - 
```
Supported features

-     Sending messages

-     Marking messages as read

-     Sending Media (images, audio, video and documents)

-     Sending location

-     Sending interactive buttons

-     Sending template messages

-     Parsing messages and media received

```
